apiVersion: apps/v1
kind: Deployment
metadata:
  name: mocksserver
  namespace: prueba-envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mocksserver
  template:
    metadata:
      labels:
        app: mocksserver
    spec:
      nodeSelector:
        karpenter.sh/nodepool: spot
      containers:
      - name: mocksserver
        image: mocksserver/main
        ports:
        - containerPort: 3100
        - containerPort: 3110
        env:
        - name: MOCKS_PATH
          value: /input
        volumeMounts:
        - mountPath: /input  # Monta el PVC completo en /input (incluye mocks/ y mocks.config.js)
          name: input-volume
        command: ["npm", "start"]
      volumes:
      - name: input-volume
        persistentVolumeClaim:
          claimName: input-pvc  # Referencia al PVC
           